@startuml

title __STRATEGY's Class Diagram__\n

  namespace com.arijeet.design.pattern.strategy {
    class com.arijeet.design.pattern.strategy.Client {
        {static} - orderList : List<Order>
        {static} + main()
        {static} - createOrders()
    }
  }
  

  namespace com.arijeet.design.pattern.strategy {
    class com.arijeet.design.pattern.strategy.Order {
        - date : LocalDate
        - id : String
        - items : Map<String, Double>
        - total : double
        + Order()
        + addItem()
        + getDate()
        + getId()
        + getItems()
        + getTotal()
    }
  }
  

  namespace com.arijeet.design.pattern.strategy {
    class com.arijeet.design.pattern.strategy.OrderDetailPrinter {
        + print()
    }
  }
  

  namespace com.arijeet.design.pattern.strategy {
    interface com.arijeet.design.pattern.strategy.OrderPrinter {
        {abstract} + print()
    }
  }
  

  namespace com.arijeet.design.pattern.strategy {
    class com.arijeet.design.pattern.strategy.PrintService {
        + PrintService()
        + printOrders()
    }
  }
  

  namespace com.arijeet.design.pattern.strategy {
    class com.arijeet.design.pattern.strategy.SummaryPrinter {
        + print()
    }
  }
  

  com.arijeet.design.pattern.strategy.OrderDetailPrinter .up.|> com.arijeet.design.pattern.strategy.OrderPrinter
  com.arijeet.design.pattern.strategy.PrintService o-- com.arijeet.design.pattern.strategy.OrderPrinter : orderPrinter
  com.arijeet.design.pattern.strategy.SummaryPrinter .up.|> com.arijeet.design.pattern.strategy.OrderPrinter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
